name: Update Helium Browser

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-helium-browser:
    name: Update Helium Browser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check if update is needed
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update-helium.sh --ci --only-check

      - name: Install Nix
        if: steps.check.outputs.should_update == 'true'
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Nix Magic Cache
        if: steps.check.outputs.should_update == 'true'
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Update version
        id: update
        if: steps.check.outputs.should_update == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update-helium.sh --ci

      - name: Commit changes
        id: commit
        if: steps.check.outputs.should_update == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "${{ steps.update.outputs.commit_message }}"
          file_pattern: "*"
    outputs:
      success: ${{ steps.update.outputs.should_update }}

  test-build:
    if: needs.update-helium-browser.outputs.success == 'true'
    continue-on-error: false
    name: Test package build
    runs-on: ubuntu-latest
    needs: update-helium-browser
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build packages
        run: |
          for package in $(nix flake show --json 2>/dev/null | jq -r '.packages.["x86_64-linux"] | keys | .[]'); do
              nix build --system 'x86_64-linux' ".#$package"
          done
